controllers:
    resource: ../src/Controller/
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\AccueilController::index

app_contact:
    path: /contact
    controller: App\Controller\ContactController::showMessageNew